
# Navbar Menus
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Service"
url = "service/"
weight = 3

[[main]]
name = "Gallery"
url = "gallery/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6
